### ISSUE TITLE
Unable to create a papertrail logger

### ISSUE THREAD

**Issue by cfroystad** [solarwinds/rkubelog#12]
We're seeing a problem in our testing environment after updating to Kubernetes 1.19.

Followed the [guide in the documentation](https://documentation.solarwinds.com/en/Success_Center/papertrail/Content/kb/configuration/rkubelog.htm) strictly and the pod starts, but soon enters CrashLoopBackOff.

The log complains about being unable to connect to the solarwinds server over tls.

The port number has been substituted by <port> but can be provided in private communication.

**Log:**
```
time="2020-12-03T08:20:11Z" level=info msg="Connecting to logs.collector.solarwinds.com:<port> over tls"
time="2020-12-03T08:20:41Z" level=error msg="Initial connection to server failed: dial tcp 3.233.129.178:<port>: i/o timeout - connection will be retried"
time="2020-12-03T08:20:41Z" level=error msg="error while creating a papertrail shipper instance: dial tcp 3.233.129.178:<port>: i/o timeout"
time="2020-12-03T08:20:41Z" level=error msg="unable to create a papertrail logger: error while creating a papertrail shipper instance: dial tcp 3.233.129.178:<port>: i/o timeout"
rkubelog: error: unable to create a papertrail log shipper, please check the provided values: unable to create a papertrail logger: error while creating a papertrail shipper instance: dial tcp 3.233.129.178:<port>: i/o timeout
```

**Comment by girishranganathan** [comment]
hello @cfroystad, can you please tell us what all environment variables have you set? Please do not share the values though :slightly_smiling_face:

**Comment by cfroystad** [comment]
Thanks for looking into this, @girishranganathan!

Here's the logging-secret created as per the documentation. If you need more information than can be shared publicly, feel free to contact me by email. I sent a support request about this issue last week, so you should have my email on file.

`kubectl create secret generic logging-secret -n kube-system --from-literal=PAPERTRAIL_PROTOCOL=tls --from-literal=PAPERTRAIL_HOST=logs.collector.solarwinds.com --from-literal=PAPERTRAIL_PORT=<port> --from-literal=LOGGLY_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

**Comment by girishranganathan** [comment]
Hello @cfroystad, you don't have to include `LOGGLY_TOKEN` if you are not using it. Also, can you please check if the values for `PAPERTRAIL_HOST` and `PAPERTRAIL_PORT` match what is in your Papertrail account?
Please go to https://papertrailapp.com/account/destinations

<img width="1674" alt="Settings_—_Papertrail" src="https://user-images.githubusercontent.com/31675149/101497953-87d90d00-3939-11eb-8af7-63e5cec9988b.png">

**Comment by cfroystad** [comment]
Thanks for getting back to me!

You got me in the right direction, and it's now working!
May I suggest some corrections for [your documentation](https://documentation.solarwinds.com/en/Success_Center/papertrail/Content/kb/configuration/rkubelog.htm):

- "_if you do not use Loggly or are simply not using rKubelog with Loggly, enter XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX to disable Loggly_" => "if you do not use Loggly or are simply not using rKubelog with Loggly, leave the value empty to disable Loggly" (Removing the value causes rkubelog to crash)

- "_Click Create and take note of the <log destination host>:<log destination port> that displays at the top of the Destination Settings page._" => "_Click Create and take note of the <log destination host>:<log destination port> that displays at the top of the relevant log destination card on the Log Destinations page._" (The value on the settings page is different and does not work)

**Comment by girishranganathan** [comment]
@cfroystad that is awesome 🎉 🎊.
Absolutely, we love to hear your feedback. I will work with the doc team on updating the doc to make it better as you have suggested.
Thanks a lot @cfroystad.

**Comment by girishranganathan** [comment]
@cfroystad if you feel this issue is resolved, can I close this issue?

**Comment by cfroystad** [comment]
On my side it's closed, thank you for your help.
As long as you track the documentation changes internally to avoid anyone else having to struggle with this, I'm happy to close this issue.

**Comment by marinoborges** [comment]
Hello @girishranganathan. I'm facing the same issue here. Tried to set LOGGLY_TOKEN to "" (empty) or "XXXX" and it keeps with the error message below:
```
time="2021-01-08T13:11:37Z" level=info msg="Connecting to logs3.papertrailapp.com:<port> over tls"
time="2021-01-08T13:12:07Z" level=error msg="Initial connection to server failed: dial tcp: i/o timeout - connection will be retried"
time="2021-01-08T13:12:07Z" level=error msg="error while creating a papertrail shipper instance: dial tcp: i/o timeout"
time="2021-01-08T13:12:07Z" level=error msg="unable to create a papertrail logger: error while creating a papertrail shipper instance: dial tcp: i/o timeout"
rkubelog: error: unable to create a papertrail log shipper, please check the provided values: unable to create a papertrail logger: error while creating a papertrail shipper instance: dial tcp: i/o timeout
```

Tried to unset LOGGLY_TOKEN and the pod doesn't start (CreateContainerConfigError).  Event `Error: couldn't find key LOGGLY_TOKEN in Secret kube-system/logging-secret`

I set the parameters as it appears in the Settings -> Log Destinations page.

@cfroystad  how did you set your parameters to make it work?

**Comment by cfroystad** [comment]
Hi there @marionborges

Here is the full command I use to configure the secret: (you must of course modify the <>-parts)

`kubectl create secret generic logging-secret -n kube-system --from-literal=PAPERTRAIL_PROTOCOL=tls --from-literal=PAPERTRAIL_HOST=<host> --from-literal=PAPERTRAIL_PORT=<portNumber> --from-literal=LOGGLY_TOKEN=`

Hope it helps!

**Comment by marinoborges** [comment]
Thanks @cfroystad! It was a name resolution issue inside the pod that couldn't reach the DNS Server. I resolved restarting coredns deployment.
