### ISSUE TITLE
Log tagging with rkubelog

### ISSUE THREAD

**Issue by jon-eicher** [solarwinds/rkubelog#15]
Is there a way to add tags to logs streamed from a kubernetes cluster to loggly using rkubelog?  With multiple kubernetes clusters logging to loggly, it would be nice to be able to tag the logs with a environment, region and clustername.

![Screen Shot 2020-12-22 at 10 01 34 AM](https://user-images.githubusercontent.com/71353830/102913916-b62c1180-443c-11eb-82d5-9bf657c54fc4.png)

**Comment by girishranganathan** [comment]
Hello @jon-eicher, we have taken an initial stab at your feature request. When you have a few can you please give the new version a try? Please checkout the new section in the readme here: https://github.com/solarwinds/rkubelog#static-tags

**Comment by girishranganathan** [comment]
I will close this issue for now. Please feel free to re-open it as needed.
